calabash/calabash-android

ruby-gem/calabash-android.gemspec
ruby-gem/lib/calabash-android/version.rb

Dependency httpclient version 2.6.x fixes two important issues:
https://github.com/nahi/httpclient/issues/84
https://github.com/nahi/httpclient/issues/185
Let's be less strict in httpclient versions supported to allow this update. But let's not force a version which would break compat with x-platform projects that don't update Calabash iOS.

Update httpclient fix keepalivedisconnected

---

ruby-gem/irbrc

`LoadError`s generated by `require` statements in `.irbrc` generate no output; they fail silently.  To the casual user, the irb appears to have loaded correctly, but in fact the evaluation of the .irbrc stops at the first exception.
We've been handling a lot of support questions about "Why aren't the calabash methods loaded in the console?".  Most of these have been because of incompatible versions of `awesome_print`.

Rescue 'awesome_print' LoadError in irbrc; don't fail silently

---

ruby-gem/calabash-android.gemspec

We should try to match the test-cloud gem retriable dependency.

Match the retriable dependency with test-cloud

---

README.md

This adds link to the README for constructing `uiquery` strings – an essential thing people need to know when using Calabash Android.

Link to Wiki for constructing uiquery strings; addresses #605

---

ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/actions/version/AndroidSDKVersion.java

Gets android SDK version. Only works on android 1.6 and later (I don’t think that’s a problem for us).

Actions: Get SDK Version

---

ruby-gem/calabash-android.gemspec

There is no reason not to allow Cucumber 2.0
https://github.com/calabash/calabash-android/issues/614

Gem: allow cucumber 2.0

---

ruby-gem/calabash-android.gemspec

There is no reason _not_ to allow Cucumber 2.0.
@TobiasRoikjer We talked about removing the dependency all together, but that would require that existing users update their Gemfiles.  I am not ready to go through the process of documenting this.
This is a good first step.
@sapieneptus @krukow @jraczak
This change will be part of Calabash iOS 0.17.
https://github.com/calabash/calabash-ios/pull/904 - merged.

Gem: relax cucumber dependency

---

ruby-gem/lib/calabash-android/canned_steps.md
ruby-gem/lib/calabash-android/steps/l10n_steps.rb

This adds support for non-numeric l10nkeys, while keeping in place compatibility with the old definitions

Fixing l10nkey to allow for non-numeric keys

---

ruby-gem/lib/calabash-android/operations.rb

Hit a problem when trying to store some json inside an Android App preference.  This fixed it on OS X, don't have access to a windows box to try it out

Use shell words on am command

---

ruby-gem/lib/calabash-android/operations.rb

Some devices may respond with Unicode characters in the `adb shell dumpsys`
output, which causes comparison to string literals to fail with:
invalid byte sequence in US-ASCII (ArgumentError) (RuntimeError)
Using `String#force_encoding(UTF-8)` fixes that.

Fix "invalid byte sequence in US-ASCII" error

---

.travis.yml

I want to try Slack notifications again for Travis CI.
Iterating with Travis support re: encrypting the token.

Travis: add #calabash-ci slack notifications

---

ruby-gem/lib/calabash-android.rb
ruby-gem/lib/calabash-android/environment.rb
ruby-gem/spec/lib/environment_spec.rb

Progress on **Add usage tracking** #655
* Need user's home directory to manage ~/.calabash
* Need CI methods for statistics
I choose to make a new file rather than add the methods to `environment_helpers.rb` or to `env.rb`
* It was easier to port to `Calabash::Android::Environment` in `environment.rb`.
* The `Env` module is defined in the _top level_ namespace and I believe it is used mostly for the build script? I think it is better to have these methods defined in the `Calabash::Android` namespace/module.
* Putting the methods in `EnvironmentHelpers` was tempting, but I opted not to put them there because we may or may not want these methods available as part of the public API.  If they were in `EnvironmentHelpers` they would be available to cucumber.

Env: port run-loop enviroment.rb

---

bin/ci/travis/run.sh
ruby-gem/calabash-android.gemspec

Resolves **Gem contains many unnecessary files** #651
To the reviewer, I left out these files:
* ruby-gems/.calabash_settings
* ruby-gems/lib/calabash-android/canned_steps.md
* ruby-gems/lib/calabash-android/removed_actions.txt
I think Tobias is the obvious reviewer.

Gem: only include necessary files in the gem

---

ruby-gem/spec/lib/logging_spec.rb

In Windows CI:
```
08:40:40   1) Calabash::Android::Logging file logging logs directory and calabash.log .log_to_file handles errors by logging when debugging
08:40:40      Failure/Error: expect(actual).to be == expected
08:40:40 
08:40:40        expected: == "DEBUG: Could not write:\n\nmessage\n\nto calabash.log because:\n\nDid not get the last hit\n\n"
08:40:40             got:    "DEBUG: Could not write:\n\nmessage\n\nto calabash.log because:\n\nDid not get the last hit\n"
08:40:40      # C:/Program Files (x86)/Jenkins/jobs/Calabash Android/workspace/ruby-gem/spec/lib/logging_spec.rb:142:in `block (5 levels) in <top (required)>'
```
Also testing Windows Jenkins CI: GHPRB

Rspec: stablize logging spec on Windows

---

ruby-gem/lib/calabash-android/operations.rb

Calabash-Android takes a long time to start the app
Increase the poll-rate for the server to be ready.
https://github.com/calabash/calabash-android/issues/670

Increase the poll-rate for the server to be ready.

---

ruby-gem/bin/calabash-android-run.rb
ruby-gem/lib/calabash-android/operations.rb

Addresses `calabash-android run` failures when using the Calabash sandbox on Windows as a user with a space in the username.  Will also support any other scenario where the path to ruby or the calabash-android gem contains a space.
@TobiasRoikjer:  Could you review and test this on OS-X please?

Handle spaces within the path to ruby/calabash-android

---

.travis.yml
bin/ci/travis/run.sh
bin/ci/windows.bat
ruby-gem/calabash-android.gemspec

Replaces: Jenkins: add a batch file for running on Windows #737
1. Jenkins is inserting unix newlines into scripts edited from Jenkins web UI - use `bin/ci/windows.bat` on Jenkins
2. redcarpet does not install on Windows and is not required there (development dependency) - don't install on Windows
3. There is no CI job on macOS - update `.travis.yml` to run on macOS and Linux
4. Limit the number of ruby versions tested on Travis.
5. Add `before_install` section to get a good version of rubygems and bundler installed

CI: update Travis configuration and fix Windows Jenkins test script

---

ruby-gem/calabash-android.gemspec
ruby-gem/lib/calabash-android/operations.rb
ruby-gem/lib/calabash-android/retry.rb
ruby-gem/lib/calabash-android/retryable.rb
ruby-gem/spec/lib/retryable_spec.rb

Approach to remove the retrieable dependency.
Since our use case is quite simple, this simple approach ought to be enough.
See #743

Remove retriable dependency

---

ruby-gem/lib/calabash-android/steps/navigation_steps.rb

perform_action('send_key_enter') has a deprecated warning  but is used in the "^I press the enter button" step defined in steps/navigation_steps.rb
press_enter_button is its direct replacement, but maybe press_user_action_button is more appropriate for a general step like this.

Fix deprecated method in "I press the enter button"

---

ruby-gem/lib/calabash-android/gestures.rb
ruby-gem/lib/calabash-android/touch_helpers.rb

touch(some_operation_which_results_in_nil_instead_of_valid_query_result) throws RuntimeError  
eg. touch(nil)  
RuntimeError: Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission  
Throwing more user-friendly exception in case query_string is nil.

touch(nil) throws INJECT_EVENTS permission

---

ruby-gem/bin/calabash-android
ruby-gem/bin/calabash-android-build.rb
ruby-gem/lib/calabash-android.rb
ruby-gem/lib/calabash-android/helpers.rb
ruby-gem/lib/calabash-android/utils.rb
ruby-gem/spec/lib/utils_spec.rb

Solution: Silence Rubyzip date warnings if the version of Rubyzip the
user is using supports it.

Problem: Rubyzip warns of invalid date in gradle APKs

---

ruby-gem/lib/calabash-android/helpers.rb

`Calabash::Utils` was introduced in version 0.8.4. The helpers.rb uses methods from it but does not `require` it.

Require Calabash::Utils in helpers.rb

---

ruby-gem/lib/calabash-android/dependencies.rb

I've experienced that the detection fails on our machines, but when the path is expanded the detection succeeds.

Expand paths when detecting Android SDK

---

ruby-gem/irbrc

All this does is wrap the logic executed by irbrc into a custom error handler that dumps the error to console.  Unfortunately, GitHub's differ is making it look like a bigger change than it is.
The old approach only rescued LoadErrors from awesomeprint, but other failures are possible outside of that.
I just ran into this as a user, on account of a brew upgrade on my laptop replacing a GNU Readline shared object that my copy of ruby built by ruby-build was depending on, causing Calabash's irbrc's `require 'irb/ext/save-history'` fail.  This patch makes such failures no longer silent.

irbrc should capture all errors: otherwise, irb silently eats them.

---

ruby-gem/lib/calabash-android/operations.rb

When updating an app (using `Calabash::Android::Operations.update_app`) from a version A with sdk version < 23 to a version B with sdk version >= 23, the android permissions are not automatically granted.
This happens because adb flags must be sent separately. `adb install -rg` will only update app, `g` option is ignored.
With `adb install -r -g` it successfully updates the app AND grants permissions.
I tested it with calabash-android 0.9.0 and adb version 1.0.36

Fix: permissions not granted on app update

---

ruby-gem/lib/calabash-android/text_helpers.rb

`Calabash::Android::TextHelpers` only provides `escape_quotes`, however this method alone doesn't account for all escaping needs.
This adds `escape_backslashes` and `escape_newlines`, which are all combined so you can call `escape_string`.

Escape string methods for TextHelpers module

---

ruby-gem/lib/calabash-android/operations.rb

`done` in `operations.rb` is no longer being used and can be safely removed.
For: https://github.com/calabash/calabash-android/issues/722

Removing done from operations to fix #722

---

ruby-gem/lib/calabash-android/monkey_helpers.rb

Solve error from https://github.com/calabash/calabash-android/issues/740
Simply reset two variables after killing process
```
@@monkey_port = nil
@@monkey_pid  = nil
```

Fixed: error when repeated calling funciton send_tcp()

---

ruby-gem/lib/calabash-android/operations.rb

Read more about the EU GDPR here:
* http://www.europarl.europa.eu/pdfs/news/expert/background/20160413BKG22980/20160413BKG22980_en.pdf
Completes:
* Remove usage tracking from Calabash Android [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/12759)
Notes:
The MixPanel account that we used to track usage has been disabled for over a year.

Remove usage tracking to comply with EU GDPR 2018

---

ruby-gem/calabash-android.gemspec

Test Cloud is not ready for Cucumber 3.0
Completes:
* Calabash Android: pin cucumber to 2.x [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29371)

Gem: pin cucumber to < 3.0

---

CHANGELOG.md
ruby-gem/lib/calabash-android/version.rb

* Gem: pin cucumber to < 3.0 #847
* Remove usage tracking to comply with EU GDPR 2018 #835
* Add check for installed app before attempting uninstall #833
* Fixed: error when repeated calling funciton send\_tcp() #821
* fix order of default\_timeout initialization and usage in wait\_for method #818
* Removing done from operations to fix #722 #812
* irbrc should capture all errors: otherwise, irb silently eats them. #810
* Fix: permissions not granted on app update #808
* Escape string methods for TextHelpers module #807
* Expand paths when detecting Android SDK #799
* Views without id should not generate log messages [#46](https://github.com/calabash/calabash-android-server/pull/46)
* Travis: ensure ant is installed [#45](https://github.com/calabash/calabash-android-server/pull/45)
* Fix …

Gem: update version to 1.9.1

---

.travis.yml
ruby-gem/calabash-android.gemspec

Progress on:
* Calabash: pin ruby clients to cucumber 2.x [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29369)
When running `rake build` and after updating the `Calabash::Android::VERSION` to "0.9.1", I discovered that the packaged gem was versioned `0.9.1.pre2`.  This is because the active calabash-android gem was 0.9.1.pre2.
We have used the technique in the run-loop and Calabash 2.0 gemspecs for several years.

Gem: do not munge the load path

---

ruby-gem/calabash-android.gemspec

Completes:
* Calabash Android:  rubyzip version has a security vulnerability [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/30194)
I am confident that this will not be disruptive to Test Cloud or locally because my local Gemfile.lock is already pinned to 1.2.1.

Update rubyzip and yard dependencies in response to security alerts

---

CONTRIBUTING.md
ruby-gem/Rakefile

Previously, `rake build` and `rake release` would trigger a build of the TestServer.apk.
Now that the TestServer.apk is part of the git index, `rake release` will fail because the TestServer.apk is touched so there are "uncommitted changes".
This pull request removes the "build server step" from the `build` and `release` rake tasks and introduces a new task: `rake build_server`.
I have updated the release instructions in the CONTRIBUTING doc.

Gem: update the way the gem is released

---

ruby-gem/calabash-android.gemspec

The gem is pinned to Cucumber <3.0 and there are new versions available. The PR change the maximum version to <3.99.
So far we see some advantages in newest Cucumber version and it would be nice to be able to use them. After bumping Cucumber locally I didn't see any issues with latest Cucumber (running ~400 tests).

Support  latest Cucumber versions

---

ruby-gem/calabash-android.gemspec

The version is quite outdated, in this way users are able to decide which version they want to use.

Do not bind Calabash to any versions of json

---

ruby-gem/lib/calabash-android/operations.rb

apk built using android studio are not getting installed. Gradle generates a test APK when you have only run or debugged your app or have used the Android Studio
https://developer.android.com/studio/command-line/adb.html#-t-option

Allow test APKs to be installed

---

ruby-gem/calabash-android.gemspec
ruby-gem/lib/calabash-android/dependencies.rb
ruby-gem/lib/calabash-android/version.rb
ruby-gem/spec/lib/version_spec.rb

Progress on:
* Calabash Stack:  remove strict json and bundler version requirements from gems [AzDevOps](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/60112)
Fixes: **Gem::ConflictError** #905
Removes the luffa dependency which was only used for the `Version` class.

gem: remove luffa dependency; add Version class

---

ruby-gem/lib/calabash-android/java_keystore.rb

With new jdk, the keytool reports 
`Signature algorithm name: SHA1withRSA (weak)`
as compared to old jdk which used to report it as:
`Signature algorithm name: SHA1withRSA`
This breaks the parsing and results in failing of apk resigning. This PR tries to fix that

Fix signing for newer keytool

---

.travis.yml

The ci running in osx is failing due to some system issue. This is preventing PRs from being merged.
Until someone with better knowledge or access to address this, we can disable the execution in osx.

Update .travis.yml to run ruby 2.7.1
