ruby-gem/irbrc, ruby-gem/lib/calabash-android/operations.rb
Fixes **screenshot_and_raise failing** [#246](https://github.com/calabash/calabash-ios/issues/246) for Calabash Android
=> Operations: React as expected when asked to embed

ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/actions/device/DpToDevicePixel.java
=> Added action to convert dp to px

ruby-gem/features-skeleton/support/app_installation_hooks.rb
Besides, remembering the actual feature instead of its name is a bit more robust.
=> Avoid poking around in structures which will change in Cucumber 2.0

ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/query/ast/UIQueryASTClassName.java, ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/query/ast/UIQueryASTPredicate.java, ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/query/ast/UIQueryASTWith.java, ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/query/ast/UIQueryUtils.java, ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/query/ast/UIQueryVisibility.java
Please review and consider for next pre-release
=> remove duplicates

ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/actions/NanoHTTPD.java
When NanoHTTPD detects a PUT it streams the data directly to a file instead of an in-memory buffer it copies multiple times.
=> Allow uploading of large files with PUT requests.

ruby-gem/calabash-android.gemspec
Not ready yet for Cucumber 2.0.
=> Revert commit 'f7037a': restrict to cucumber ~> 1.3.17

ruby-gem/calabash-android.gemspec
=> Gem: add license to gemspec

ruby-gem/lib/calabash-android/wait_helpers.rb, ruby-gem/spec/lib/wait_helpers_spec.rb
Resolves **unfreeze the DEFAULT_OPTS** #596
ATTN: @niekske
The rspec test is pretty pointless, but I am trying lead by example.
=> Wait: unfreeze the default options

README.md
https://github.com/calabash/install
* Update docs to discuss calabash sandbox [#20](https://github.com/xamarinhq/test-cloud-frameworks/issues/20)
=> Docs: update README with sandbox info

documentation/ruby_api.md
Reverts calabash/calabash-android#688
=> Revert "Update ruby_api.md"

.travis.yml, ruby-gem/bin/calabash-android, ruby-gem/bin/calabash-android-build.rb, ruby-gem/calabash-android.gemspec, ruby-gem/lib/calabash-android/dependencies.rb, ruby-gem/lib/calabash-android/environment.rb, ruby-gem/lib/calabash-android/helpers.rb, ruby-gem/lib/calabash-android/java_keystore.rb, ruby-gem/lib/calabash-android/operations.rb
This is the implementation from Calabash 2.0
=> Add better environment dependency detection (JDK, Android)

ruby-gem/calabash-android.gemspec
This is the last version to support ruby < 2.2
=> Gem: pin listen to 3.0.6

ruby-gem/lib/calabash-android/operations.rb
=> Fixed runtime error if system failed to update app

ruby-gem/lib/calabash-android/dependencies.rb
Detects Android SDK when installed in default location with Android Studio
=> Detect Android SDK from Android Studio

ruby-gem/calabash-android.gemspec
https://jira.xamarin.com/browse/TCFW-85
Sorry Tobias, I was not able to test this at all.
Best guess - not a problem.
=> Gem: force HTTPClient 2.7.1 or higher

ruby-gem/lib/calabash-android/store/preferences.rb, ruby-gem/lib/calabash-android/usage_tracker.rb, ruby-gem/spec/lib/usage_tracker_spec.rb
related to https://github.com/calabash/calabash-android/issues/676
=> Replace user_id with distinct_id

ruby-gem/lib/calabash-android/wait_helpers.rb
How does this look as a fix for https://github.com/calabash/calabash-android/issues/702?
=> Properly use the DEFAULT_OPTS

README.md
Adding details about the sunsetting of calabash.
=> Adding sunsetting statement to README.md

ruby-gem/Rakefile
=> Raise an exception when android-server version is different from the gem version

documentation/installation.md
Fixes #897 
I am not sure if this is the correct link for the guide. If it isn't, I can change it
=> Fix dead link on Installation guide

CHANGELOG.md, ruby-gem/lib/calabash-android/version.rb
=> Increased version number

CHANGELOG.md, ruby-gem/lib/calabash-android/operations.rb, ruby-gem/lib/calabash-android/version.rb, ruby-gem/lib/calabash-android/wait_helpers.rb
embed is not available since cucumber 5, this PR will make sure the attach is called in cases embed is not available
=> Support cucumber 6

ruby-gem/integration-tests/NativeTestApp/app/src/main/java/com/xamarin/xtcandroidsample/WebViewActivity.java
https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/TestCloud/Backlog%20Items/?workitem=98111
=> Remove aws
